-- AlterTable
ALTER TABLE `movies` MODIFY `status` ENUM('PUBLISHED', 'PENDING', 'ARCHIVED', 'UPCOMING') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `series` MODIFY `status` ENUM('PENDING', 'PUBLISHED', 'ENDED', 'CANCELED', 'ARCHIVED', 'UPCOMING') NOT NULL DEFAULT 'PENDING';
